import Link from "next/link";
import { ArrowRight, BadgeCheck, Check, CirclePlay, Sparkles, Star, Zap } from "lucide-react";
import { CTA } from "@/components/festusg-shell";
import { projects, services, steps, testimonials } from "@/components/festusg-data";
export default function Home(){const studioImage=`${process.env.NEXT_PUBLIC_BASE_PATH??""}/festusg-studio-green.jpg`;return <main><section className="hero section-shell"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> Creative digital studio</div><h1>Creative Designs That Bring Your <em>Ideas to Life</em></h1><p>FestusG creates modern websites, eye-catching graphics, AI videos, promotional materials and memorable designs for individuals, businesses and special occasions.</p><div className="hero-actions"><Link href="/portfolio" className="button">View My Work <ArrowRight size={18}/></Link><Link href="/contact" className="button ghost">Start a Project</Link></div><div className="trust-row"><span><BadgeCheck size={18}/> Tailored design</span><span><Zap size={18}/> Fast delivery</span></div></div><div className="hero-visual"><div className="hero-glow"/><img src={studioImage} alt="FestusG creative design studio"/><div className="float-card float-one"><b>8+ services</b><small>One creative partner</small></div><div className="float-card float-two"><CirclePlay size={26}/><div><b>AI video</b><small>Ideas in motion</small></div></div></div></section><section className="ticker"><div>Website Design <i/> Graphic Design <i/> AI Video <i/> Brand Visuals <i/> Event Designs <i/> Social Media <i/></div></section>
<section className="section section-shell"><div className="section-head"><div><div className="section-label">What I create</div><h2>Creative Services for <span>Every Big Idea</span></h2></div><Link href="/services" className="text-link">Explore all services <ArrowRight size={16}/></Link></div><div className="service-grid home-grid">{services.slice(0,4).map(({icon:Icon,title,text},i)=><article className="service-card" key={title}><div className="service-top"><div className="icon-wrap"><Icon size={22}/></div><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><Link href="/services">Learn More <ArrowRight size={14}/></Link></article>)}</div></section>
<section className="section portfolio-section"><div className="section-shell"><div className="section-head"><div><div className="section-label">Selected work</div><h2>Ideas Turned Into <span>Visual Experiences</span></h2></div><Link href="/portfolio" className="text-link">View full portfolio <ArrowRight size={16}/></Link></div><div className="project-grid">{projects.slice(0,3).map((p,i)=><article className={`project-card ${i===0?"featured":""}`} key={p.title}><div className={`project-image ${p.tone}`} role="img" aria-label={`${p.title} creative project preview`} style={{backgroundImage:`url(${studioImage})`,backgroundPosition:p.pos}}><span>{p.category}</span></div><div className="project-meta"><div><h3>{p.title}</h3><p>{p.desc}</p></div></div></article>)}</div></div></section>
<section className="section section-shell"><div className="process-intro"><div><div className="section-label">How it works</div><h2>A Clear Process. <span>A Better Result.</span></h2></div><Link href="/process" className="text-link">See how we work <ArrowRight size={16}/></Link></div><div className="steps">{steps.map(([n,t,d],i)=><article key={n}><div className="step-number">{n}</div>{i<3&&<div className="step-line"/>}<h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section testimonials-section"><div className="section-shell"><div className="section-head"><div><div className="section-label">Client feedback</div><h2>Trusted for <span>Great Creative Work</span></h2></div><Link href="/testimonials" className="text-link">Read client stories <ArrowRight size={16}/></Link></div><div className="testimonial-grid">{testimonials.slice(0,3).map(([initials,name,service,review])=><article key={name}><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={15} fill="currentColor"/>)}</div><p>“{review}”</p><div className="client"><div>{initials}</div><span><b>{name}</b><small>{service}</small></span></div></article>)}</div></div></section><CTA/></main>}
