"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Mail, Menu, MessageCircle, Phone, X } from "lucide-react";

const links = [["Home","/"],["About Us","/about"],["Services","/services"],["Portfolio","/portfolio"],["Process","/process"],["Testimonials","/testimonials"],["Contact Us","/contact"]];
export function Brand(){return <Link href="/" className="brand"><span>F</span>Festus<span>G</span></Link>}
export function MovingBackdrop(){const items=["WEB DESIGN","FLYERS","AI VIDEO","POSTERS","BANNERS","INVITATIONS","SOCIAL GRAPHICS","CUSTOM DESIGN"];return <div className="moving-backdrop" aria-hidden="true">{items.map((item,i)=><span key={item} style={{"--i":i} as React.CSSProperties}>{item}</span>)}</div>}
export function Header(){const [open,setOpen]=useState(false);return <header className="header"><div className="nav-shell"><Brand/><nav className={open?"nav-links open":"nav-links"}>{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/contact" className="button small mobile-cta">Start a Project</Link></nav><Link href="/contact" className="button small desktop-cta">Start a Project <ArrowRight size={15}/></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></header>}
export function Footer(){return <footer><div className="section-shell footer-intro"><div><span>Have something in mind?</span><h2>Let’s make your next idea stand out.</h2></div><Link href="/contact" className="button">Start a Project <ArrowRight size={17}/></Link></div><div className="section-shell footer-grid"><div><Brand/><p>Creative websites, graphics and digital experiences designed to make ideas memorable.</p><div className="socials"><a href="mailto:festusginah1@gmail.com" aria-label="Email FestusG"><Mail/></a><a href="tel:+2348062707011" aria-label="Call FestusG"><Phone/></a><a href="https://wa.me/2348062707011" target="_blank" rel="noreferrer" aria-label="Chat with FestusG on WhatsApp"><MessageCircle/></a></div></div><div><h4>Explore</h4>{links.slice(1,6).map(([x,h])=><Link href={h} key={h}>{x}</Link>)}</div><div><h4>Services</h4><Link href="/services">Website Design</Link><Link href="/services">Flyers & Posters</Link><Link href="/services">AI Video Creation</Link><Link href="/services">Social Media Graphics</Link></div><div><h4>Contact</h4><a href="mailto:festusginah1@gmail.com">festusginah1@gmail.com</a><a href="mailto:festusginah25@gmail.com">festusginah25@gmail.com</a><a href="tel:+2348062707011">08062707011</a><a href="tel:+2348122898289">08122898289</a><a href="https://wa.me/2348062707011" target="_blank" rel="noreferrer">WhatsApp</a><span>No. 1, Off Nikton Road, Kpansia, Yenagoa, Bayelsa State</span></div></div><div className="section-shell footer-bottom"><span>© {new Date().getFullYear()} FestusG. All rights reserved.</span><div><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></div></div></footer>}
export function PageHero({label,title,accent,copy}:{label:string,title:string;accent:string;copy:string}){return <section className="page-hero section-shell"><div className="section-label">{label}</div><h1>{title} <span>{accent}</span></h1><p>{copy}</p></section>}
export function CTA(){return <section className="cta section-shell"><div><div className="section-label light">Let’s create something remarkable</div><h2>Have a Creative Idea?<br/>Let’s Bring It to Life.</h2><p>Whether you need a website, promotional design, AI video or personalised celebration card, FestusG is ready to help.</p><Link href="/contact" className="button white">Start Your Project <ArrowRight size={18}/></Link></div><div className="cta-orbit"><span/><span/></div></section>}
